import type {
  ResumeProfile,
  TailoredResume,
  MatchScore,
  JobDescriptionProfile,
  GapAnalysis,
} from "./types";

export function generateMarkdown(
  resume: ResumeProfile,
  tailored: TailoredResume,
  jd: JobDescriptionProfile,
  score: MatchScore | null,
  gaps: GapAnalysis | null
): string {
  const lines: string[] = [];

  lines.push(`# ${resume.contact?.name ?? "Candidate"} — Tailored Resume`);
  lines.push("");

  // Contact
  const contactParts: string[] = [];
  if (resume.contact?.email) contactParts.push(resume.contact.email);
  if (resume.contact?.phone) contactParts.push(resume.contact.phone);
  if (resume.contact?.linkedin) contactParts.push(resume.contact.linkedin);
  if (contactParts.length > 0) {
    lines.push(`**${contactParts.join(" | ")}**`);
    lines.push("");
  }

  // Target
  lines.push(`> Tailored for: **${jd.jobTitle}**${jd.company ? ` at ${jd.company}` : ""}`);
  lines.push("");

  // Score
  if (score) {
    lines.push(`## Match Score: ${score.overallScore}/100`);
    lines.push("");
    lines.push(`- Skill Coverage: ${score.skillCoverageScore}/100`);
    lines.push(`- Responsibility Alignment: ${score.responsibilityAlignmentScore}/100`);
    lines.push(`- Keyword Match: ${score.keywordScore}/100`);
    lines.push(`- Seniority Match: ${score.seniorityScore}/100`);
    if (score.explanation) {
      lines.push("");
      lines.push(`> ${score.explanation}`);
    }
    lines.push("");
  }

  // Summary
  if (tailored.tailoredSummary) {
    lines.push("## Professional Summary");
    lines.push("");
    lines.push(tailored.tailoredSummary);
    lines.push("");
  }

  // Skills
  lines.push("## Skills");
  lines.push("");
  lines.push(tailored.tailoredSkills.join(", "));
  lines.push("");

  // Experience
  lines.push("## Experience");
  lines.push("");
  for (const exp of tailored.tailoredExperience) {
    lines.push(`### ${exp.title} — ${exp.company}`);
    lines.push("");
    for (const bullet of exp.bullets) {
      const confidenceIcon =
        bullet.confidence === "high"
          ? "✓"
          : bullet.confidence === "medium"
          ? "⚠"
          : "✗";
      lines.push(`- ${bullet.tailored} _[${confidenceIcon} ${bullet.confidence} confidence]_`);
    }
    lines.push("");
  }

  // Education
  if (resume.education && resume.education.length > 0) {
    lines.push("## Education");
    lines.push("");
    for (const edu of resume.education) {
      const parts = [edu.institution];
      if (edu.degree) parts.push(edu.degree);
      if (edu.field) parts.push(edu.field);
      if (edu.graduationDate) parts.push(`(${edu.graduationDate})`);
      lines.push(`- ${parts.join(" — ")}`);
    }
    lines.push("");
  }

  // Certifications
  if (resume.certifications && resume.certifications.length > 0) {
    lines.push("## Certifications");
    lines.push("");
    for (const cert of resume.certifications) {
      lines.push(`- ${cert.name}${cert.issuer ? ` — ${cert.issuer}` : ""}`);
    }
    lines.push("");
  }

  // Gap Analysis
  if (gaps && gaps.gaps.length > 0) {
    lines.push("## Gap Analysis");
    lines.push("");
    lines.push("| Gap | Importance | Suggested Action |");
    lines.push("|-----|------------|------------------|");
    for (const gap of gaps.gaps) {
      lines.push(`| ${gap.name} | ${gap.importance} | ${gap.suggestedAction} |`);
    }
    lines.push("");
  }

  // Risk Flags
  const riskFlags: { expIdx: number; bIdx: number; desc: string }[] = [];
  tailored.tailoredExperience.forEach((exp, expIdx) => {
    exp.bullets.forEach((b, bIdx) => {
      if (b.riskFlag && b.confidence === "low") {
        riskFlags.push({ expIdx, bIdx, desc: b.riskFlag });
      }
    });
  });
  if (riskFlags.length > 0) {
    lines.push("## ⚠ Risk Flags");
    lines.push("");
    for (const rf of riskFlags) {
      lines.push(`- ${rf.desc}`);
    }
    lines.push("");
  }

  // Disclaimer
  lines.push("---");
  lines.push(
    `*Generated by Resume Shapeshifter AI for ${jd.jobTitle}${
      jd.company ? ` at ${jd.company}` : ""
    }. Verify all information before use.*`
  );

  return lines.join("\n");
}